# Project-1 | Statistical Learning | La Liga

In [308]:
import pandas as pd
import numpy as np

In [309]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [310]:
laliga = pd.read_csv("Laliga.csv",header=1)
type(laliga)
laliga.head()
laliga.describe()
laliga_names=pd.DataFrame(laliga.dtypes)
laliga_names.columns
laliga.shape

pandas.core.frame.DataFrame

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

             Pos    Seasons  BestPosition
count  61.000000  61.000000     61.000000
mean   31.000000  24.000000      7.081967
std    17.752934  26.827225      5.276663
min     1.000000   1.000000      1.000000
25%    16.000000   4.000000      3.000000
50%    31.000000  12.000000      6.000000
75%    46.000000  38.000000     10.000000
max    61.000000  86.000000     20.000000

RangeIndex(start=0, stop=1, step=1)

(61, 20)

# Question 1

In [311]:
print("**************Convert all dashes to 0 *******************")
laliga=laliga.replace("-", 0)

laliga_names=laliga_names.loc[laliga_names.index!='Team']
laliga_names=laliga_names.loc[laliga_names.index!='Debut']
laliga_names=laliga_names.loc[laliga_names.index!='Since/LastApp']
laliga_names= laliga_names.loc[laliga_names[0]=="object",:]
laliga_names
laliga[laliga_names.index] = laliga[laliga_names.index].apply(pd.to_numeric)
laliga.describe()
laliga.head(3)

**************Convert all dashes to 0 *******************

                   0
Points        object
GamesPlayed   object
GamesWon      object
GamesDrawn    object
GamesLost     object
GoalsFor      object
GoalsAgainst  object
Champion      object
Runner-up     object
Third         object
Fourth        object
Fifth         object
Sixth         object
T             object

,Pos,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,BestPosition
count,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000
mean,31.000000,24.000000,901.426230,796.819672,303.967213,188.934426,303.754098,1140.344262,1140.229508,1.426230,1.409836,1.409836,1.409836,1.409836,1.409836,8.475410,7.081967
std,17.752934,26.827225,1134.899121,876.282765,406.991030,201.799477,294.708594,1506.740211,1163.710766,5.472535,4.540107,3.247445,2.746980,2.505840,2.231420,18.100282,5.276663
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,16.000000,4.000000,96.000000,114.000000,34.000000,24.000000,62.000000,153.000000,221.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
50%,31.000000,12.000000,375.000000,423.000000,123.000000,95.000000,197.000000,430.000000,632.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000
75%,46.000000,38.000000,1351.000000,1318.000000,426.000000,330.000000,563.000000,1642.000000,1951.000000,0.000000,0.000000,1.000000,2.000000,2.000000,2.000000,6.000000,10.000000
max,61.000000,86.000000,4385.000000,2762.000000,1647.000000,633.000000,1070.000000,5947.000000,3889.000000,33.000000,25.000000,16.000000,12.000000,12.000000,10.000000,83.000000,20.000000

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1

# Quesion 2

In [312]:
laliga["Debut"]=laliga["Debut"].str.slice(start=0,stop=4)
laliga["Debut"]=pd.to_numeric(laliga["Debut"])

laliga1980=laliga[(laliga["Debut"]>=1930) & (laliga["Debut"]<=1980)]
print("Teams That Debuted between 1930 and 1980")
laliga1980.groupby("Team")["Debut"].agg("min").sort_values()

Teams That Debuted between 1930 and 1980

Team
Alaves                 1930
Valencia               1931
Real Betis             1932
Oviedo                 1933
Sevilla                1934
Osasuna                1935
Hercules               1935
Zaragoza               1939
Celta Vigo             1939
Murcia                 1940
Deportivo La Coruna    1941
Granada                1941
Castellon              1941
Sabadell               1943
Sporting Gijon         1944
Alcoyano               1945
Gimnastic              1947
Valladolid             1948
Malaga                 1949
Lleida                 1950
Atletico Tetuan        1951
Las Palmas             1951
Jaen                   1953
Cultural Leonesa       1955
Condal                 1956
Elche                  1959
Mallorca               1960
Tenerife               1961
Cordoba                1962
Levante                1963
Pontevedra             1963
Burgos CF              1971
Salamanca              1974
Rayo Vallecano         1977
Cadiz                  1977
Recreativo             1978
AD Almeria             1979
Name: Debut, dtype: int64

# Question 3

In [313]:
print("TOP 5 teams in terms of points")



laliga=laliga.sort_values(by="Points",ascending=False)

print("Top 5 teams with best winning percentage")
laliga[["Team","Points"]].head(5)

TOP 5 teams in terms of points
Top 5 teams with best winning percentage

              Team  Points
0      Real Madrid    4385
1        Barcelona    4262
2  Atletico Madrid    3442
3         Valencia    3386
4  Athletic Bilbao    3368

# Question 4

In [314]:

def Goal_diff_count():
    Goal_diff_count =laliga["GoalsFor"] - laliga["GoalsAgainst"]
    Goal_diff_count.index=laliga["Team"]
    max_index=Goal_diff_count.idxmax()
    min_index=Goal_diff_count.idxmin()
    return Goal_diff_count,max_index,min_index
laliga4=Goal_diff_count()

print("Goal DIfference for all teams ", laliga4[0])
print("Team with Highest Goal Difference ", laliga4[1])
print("Team with Lowest Goal Difference ", laliga4[2])

Goal DIfference for all teams  Team
Real Madrid            2807
Barcelona              2786
Atletico Madrid        1225
Valencia                929
Athletic Bilbao         931
Sevilla                 307
Espanyol               -280
Real Sociedad            -2
Zaragoza               -164
Real Betis             -333
Deportivo La Coruna    -136
Celta Vigo             -346
Valladolid             -413
Racing Santander       -525
Sporting Gijon         -399
Osasuna                -334
Malaga                 -342
Oviedo                 -309
Mallorca               -189
Las Palmas             -399
Villarreal              103
Granada                -338
Rayo Vallecano         -328
Elche                  -272
Getafe                 -113
Hercules               -334
Tenerife               -125
Murcia                 -385
Alaves                 -165
Levante                -202
                       ...
Sabadell               -228
Cadiz                  -269
Logrones               -198
Castellon              -169
Albacete                -90
Almeria                -122
Cordoba                -145
Compostela              -42
Recreativo              -94
Burgos CF               -94
Pontevedra              -56
Numancia                -98
Eibar                   -28
Arenas                  -81
Real Burgos             -38
Gimnastic              -114
Extremadura             -55
Merida                  -45
Alcoyano               -107
Jaen                    -62
Real Union              -31
AD Almeria              -45
Europa                  -34
Lleida                 -112
Leganes                 -19
Xerez                   -28
Condal                  -20
Atletico Tetuan         -34
Cultural Leonesa        -31
Girona                    0
Length: 61, dtype: int64
Team with Highest Goal Difference  Real Madrid
Team with Lowest Goal Difference  Racing Santander

# Question 5

In [315]:
laliga["Winning_percent"]=(laliga["GamesWon"] / laliga["GamesPlayed"])*100
laliga=laliga.sort_values(by="Winning_percent",ascending=False)

print("Top 5 teams with best winning percentage")
laliga[["Team","Winning_percent"]].head(5)

Top 5 teams with best winning percentage

              Team  Winning_percent
0      Real Madrid        59.630702
1        Barcelona        57.241130
2  Atletico Madrid        47.475134
3         Valencia        44.557057
4  Athletic Bilbao        43.772629

# Question 6

In [316]:
print("Sum of Points by Best Position")
laliga.groupby("BestPosition")["Points"].agg("sum")

BestPosition
1     27933
2      6904
3      5221
4      6563
5      1884
6      2113
7      1186
8      1134
9        96
10      450
11      445
12      511
14       71
15       14
16       81
17      266
19       81
20       34
Name: Points, dtype: int64